//
//  SignUpModels.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SignUpEnum {
    // MARK: Use cases
    
    enum SignUpAction {
        struct Request {
            let id: String
            let username: String
            let password: String
            let email: String
            let gender: String
            let creditCard: String
            let bio: String
        }
        struct Response {
            var success: Bool
        }
        struct ViewModel {
            let showModal: Bool
            let textMessage: String
        }
    }
}
