//
//  SignUpInteractor.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpBusinessLogic
{
    func doSomething(request: SignUpEnum.Something.Request)
}

protocol SignUpDataStore
{
  //var name: String { get set }
}

class SignUpInteractor: SignUpBusinessLogic, SignUpDataStore
{
  var presenter: SignUpPresentationLogic?
  var worker: SignUpWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func doSomething(request: SignUpEnum.Something.Request)
  {
    worker = SignUpWorker()
    worker?.doSomeWork()
    
    let response = SignUpEnum.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
