//
//  SignUpRouter.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignUpRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SignUpDataPassing
{
  var dataStore: SignUpDataStore? { get }
}

class SignUpRouter: NSObject, SignUpRoutingLogic, SignUpDataPassing
{
  weak var viewController: SignUpViewController?
  var dataStore: SignUpDataStore?
  
  // MARK: Routing
}
