//
//  SignUpPresenter.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignUpPresentationLogic
{
    func presentSomething(response: SignUpEnum.Something.Response)
}

class SignUpPresenter: SignUpPresentationLogic
{
  weak var viewController: SignUpDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: SignUpEnum.Something.Response)
  {
    let viewModel = SignUpEnum.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
