//
//  UserInfoPresenter.swift
//  GShop
//
//  Created by Matthew on 12.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserInfoPresentationLogic {
    func presentShow(response: UserInfoModel.Show.Response)
    func presentUpdate(response: UserInfoModel.Update.Response)
}

class UserInfoPresenter: UserInfoPresentationLogic {
    weak var viewController: UserInfoDisplayLogic?
    
    // MARK: Do something
    
    func presentShow(response: UserInfoModel.Show.Response){
        let viewModel = UserInfoModel.ViewModel(
            showModal: false,
            textMessage: "",
            email: response.email,
            username: response.username,
            gender: response.gender,
            bio: response.bio
        )
        self.viewController?.updateView(viewModel: viewModel)
    }
    
    func presentUpdate(response: UserInfoModel.Update.Response) {
        DispatchQueue.main.async {
            var viewModel = UserInfoModel.ViewModel(
                showModal: true,
                textMessage: "Success",
                email: response.email,
                username: response.username,
                gender: response.gender,
                bio: response.bio)
            
            if !response.success {
                viewModel.showModal = true
                viewModel.textMessage = "Fail"
            }
            self.viewController?.updateView(viewModel: viewModel)
        }
    }
}
