//
//  UserInfoInteractor.swift
//  GShop
//
//  Created by Matthew on 12.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserInfoBusinessLogic {
    func updateUserInfo(request: UserInfo.Update.Request)
    func fetchUserInfo(request: UserInfo.Update.Request)
}

protocol UserInfoDataStore {
    //var name: String { get set }
}

class UserInfoInteractor: UserInfoBusinessLogic, UserInfoDataStore {
    var presenter: UserInfoPresentationLogic?
    private let updateUserInfo = RequestFactory().makeChangeUserDataRequestFatory()
    // MARK: Do something
    
    // MARK:
    func updateUserInfo(request: UserInfo.Update.Request) {
        updateUserInfo.changeUserData(
            id: "1",
            username: request.username,
            password: request.password,
            email: request.email,
            gender: request.gender,
            creditCard: request.creditCard,
            bio: request.bio,
            completionHandler: { resp in
                switch resp.result {
                case .success(let model):
                    self.presenter?.presentUpdate(response: UserInfo.Update.Response(success: true))
                case .failure:
                    self.presenter?.presentUpdate(response: UserInfo.Update.Response(success: false))
                }
            }
        )
    }
    
    func fetchUserInfo(request: UserInfo.Update.Request) {
        
    }

}
