//
//  UserInfoRouter.swift
//  GShop
//
//  Created by Matthew on 12.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserInfoRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UserInfoDataPassing {
    var dataStore: UserInfoDataStore? { get }
}

class UserInfoRouter: NSObject, UserInfoRoutingLogic, UserInfoDataPassing {
    weak var viewController: UserInfoViewController?
    var dataStore: UserInfoDataStore?
    
    // MARK: Routing
}
