//
//  UserInfoPresenter.swift
//  GShop
//
//  Created by Matthew on 12.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserInfoPresentationLogic {
    func presentUpdate(response: UserInfo.Update.Response)
}

class UserInfoPresenter: UserInfoPresentationLogic {
    weak var viewController: UserInfoDisplayLogic?
    
    // MARK: Do something
    
    func presentUpdate(response: UserInfo.Update.Response) {
        DispatchQueue.main.async {
            if response.success {
              let viewModel = UserInfo.ViewModel(
                showModal: true,
                textMessage: "Success")
                self.viewController?.updateView(viewModel: viewModel)
            } else {
                let viewModel = UserInfo.ViewModel(
                  showModal: true,
                  textMessage: "Fail")
                self.viewController?.updateView(viewModel: viewModel)
            }
        }
    }
}
