//
//  UserInfoModels.swift
//  GShop
//
//  Created by Matthew on 12.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserInfo {
    // MARK: Use cases
    
    enum Update {
        struct Request {
            let username: String
            let password: String
            let email: String
            let gender: String
            let creditCard: String
            let bio: String
        }
        struct Response {
            let success: Bool
        }
        
    }
    
    struct ViewModel {
        var showModal: Bool = false
        var textMessage: String = ""
        let username: String = ""
        let password: String = ""
        let email: String = ""
        let gender: String = ""
        let creditCard: String = ""
        let bio: String = ""
    }
    
    enum Fetch {
        struct Request {
        }
        struct Response { 
        }
    }
}
