//
//  CartPresenter.swift
//  GShop
//
//  Created by Matthew on 24.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartPresentationLogic {
    func presentSomething(response: Cart.Something.Response)
}

class CartPresenter: CartPresentationLogic {
    weak var viewController: CartDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Cart.Something.Response) {
        let viewModel = Cart.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
