//
//  CartModels.swift
//  GShop
//
//  Created by Matthew on 24.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CartModel {
    // MARK: Use cases
    
    enum Fetch {
        struct Request {
        }
        enum Response {
            case success(Cart)
            case failure
        }
    }
    
    enum Checkout {
        struct Request {
        }
        enum Response {
            case success
            case failure
        }
        
    }
    
    struct ViewModel {
        var showCheckoutButton: Bool = false
        var items: [CartItem]?
        var totalPrice: String = ""
        
        var showModal: Bool = false
        var textMessage: String = ""
    }
}
