//
//  CartPresenter.swift
//  GShop
//
//  Created by Matthew on 24.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartPresentationLogic {
    func presentCheckout(response: Cart.Checkout.Response)
    func presentFetch(response: Cart.Fetch.Response)
}

class CartPresenter: CartPresentationLogic {
    weak var viewController: CartDisplayLogic?
    
    // MARK: Do something
    
    func presentCheckout(response: Cart.Checkout.Response) {
        DispatchQueue.main.async {
            var viewModel = Cart.ViewModel()
            viewModel.showModal = true
            viewModel.textMessage = "Success checkout"
            self.viewController?.updateScene(viewModel: viewModel)
        }
    }
    
    func presentFetch(response: Cart.Fetch.Response) {
        
    }
}
