//
//  CartInteractor.swift
//  GShop
//
//  Created by Matthew on 24.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CartBusinessLogic {
    func fetch(request: CartModel.Fetch.Request)
    func checkout(request: CartModel.Checkout.Request)
}

protocol CartDataStore {
    //var name: String { get set }
}

class CartInteractor: CartBusinessLogic, CartDataStore {
    var presenter: CartPresentationLogic?
    //var fetchWorker:
    var checkoutWorker: CartCheckoutRequestFactory?
    var fetchWorker: CartShowRequestFactory?
    
    // MARK: Do something
    func fetch(request: CartModel.Fetch.Request) {
        fetchWorker?.show(
            cartId: 0,
            completionHandler: { resp in
                switch resp.result {
                case .success(let model):
                    self.presenter?.presentFetch(response: .success(model))
                case .failure:
                    self.presenter?.presentFetch(response: .failure)
                }
            }
        )
    }
    
    func checkout(request: CartModel.Checkout.Request) {
        
        
        checkoutWorker?.checkout(
            cartId: 0, 
            completionHandler: { resp in
                switch resp.result {
                case .success(let model):
                    self.presenter?.presentCheckout(response: .success)
                case .failure:
                    self.presenter?.presentCheckout(response: .failure)
                }
            }
        )
        
    }
}
