//
//  ProductModels.swift
//  GShop
//
//  Created by Matthew on 22.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductModel {
    // MARK: Use cases
    
    enum Fetch {
        struct Request {
        }
        
        enum Response {
            case successProductInfo(ProductById)
            case successProductReviews([Review])
            case failure
        }
        
        struct ViewModel {
            var product: ProductById?
            var reviews: [Review]?
        }
    }
}
