//
//  ProductInteractor.swift
//  GShop
//
//  Created by Matthew on 22.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductBusinessLogic {
    func doSomething(request: Product.Something.Request)
}

protocol ProductDataStore {
    //var name: String { get set }
}

class ProductInteractor: ProductBusinessLogic, ProductDataStore
{
    var presenter: ProductPresentationLogic?
    var worker: ProductWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Product.Something.Request) {
        worker = ProductWorker()
        worker?.doSomeWork()
        
        let response = Product.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
