//
//  ProductPresenter.swift
//  GShop
//
//  Created by Matthew on 22.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductPresentationLogic {
    func presentSomething(response: Product.Something.Response)
}

class ProductPresenter: ProductPresentationLogic {
    weak var viewController: ProductDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Product.Something.Response) {
        let viewModel = Product.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
