//
//  LogInModels.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LogIn {
    // MARK: Use cases
    
    
    enum LoginAction {
        struct Request {
            let login: String
            let password: String
        }
        enum Response {
            case success
            case failure
        }
        struct ViewModel {
            var showModal: Bool = false
            var textMessage: String = ""
            var redirectToUserInfo: Bool = false
        }
    }
}
