//
//  LogInRouter.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LogInRoutingLogic {
    func routeToUserInfo(segue: UIStoryboardSegue?)
}

protocol LogInDataPassing {
    var dataStore: LogInDataStore? { get }
}

class LogInRouter: NSObject, LogInRoutingLogic, LogInDataPassing {
    weak var viewController: LogInViewController?
    var dataStore: LogInDataStore?
    
    // MARK: Routing
    @objc func routeToUserInfo(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard
                segue.destination is UITabBarController,
                let tabBarController = segue.destination as? UITabBarController,
                let userInfoViewController = tabBarController.viewControllers?.first(where: { $0 is UserInfoViewController }),
                let destinationVC = userInfoViewController as? UserInfoViewController,
                let router = destinationVC.router,
                var destinationDS = router.dataStore
            else {
                return
            }
            passDataToUserInfo(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard
                let destinationVC = storyboard.instantiateViewController(withIdentifier: "UserInfoViewController") as? UserInfoViewController,
                let router = destinationVC.router,
                var destinationDS = router.dataStore
            else { return }
            
            passDataToUserInfo(source: dataStore!, destination: &destinationDS)
            navigateToUserInfo(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    func navigateToUserInfo(source: LogInViewController, destination: UserInfoViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToUserInfo(source: LogInDataStore, destination: inout UserInfoDataStore) {
        destination.userInfo = source.userInfo
    }
}
