//
//  LogInPresenter.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInPresentationLogic {
    func presentSomething(response: LogIn.Something.Response)
}

class LogInPresenter: LogInPresentationLogic {
    weak var viewController: LogInDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: LogIn.Something.Response) {
        let viewModel = LogIn.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
