//
//  LogInInteractor.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInBusinessLogic {
    func doSomething(request: LogIn.Something.Request)
}

protocol LogInDataStore {
    //var name: String { get set }
}

class LogInInteractor: LogInBusinessLogic, LogInDataStore {
    var presenter: LogInPresentationLogic?
    var worker: LogInWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: LogIn.Something.Request) {
        worker = LogInWorker()
        worker?.doSomeWork()
        
        let response = LogIn.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
