//
//  LogInPresenter.swift
//  GShop
//
//  Created by Matthew on 11.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LogInPresentationLogic {
    func present(response: LogIn.LoginAction.Response)
}

class LogInPresenter: LogInPresentationLogic {
    weak var viewController: LogInDisplayLogic?
    
    // MARK: Do something
    
    func present(response: LogIn.LoginAction.Response) {
        DispatchQueue.main.async {
            switch response {
            case .success:
                let viewModel = LogIn.LoginAction.ViewModel(
                    redirectToUserInfo: true)
                self.viewController?.displayResult(viewModel: viewModel)
            case .failure:
                let viewModel = LogIn.LoginAction.ViewModel(
                    showModal: true,
                    textMessage: "Fail")
                self.viewController?.displayResult(viewModel: viewModel)
            }
        }
    }
}
