# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :project do
    # add actions here: https://docs.fastlane.tools/actions
    ensure_git_status_clean
    clear_derived_data
    xcclean(
        scheme: "GShop",
        workspace: "GShop.xcworkspace"
    )
    
    cocoapods(
        use_bundle_exec: false
    )
    capture_ios_screenshots
  
    increment_build_number
    gym(
      scheme: "GShop",
      configuration: "Debug",
      export_method: "development",
      include_symbols: true,
      include_bitcode: true,
      silent: false
    )
    
    # commit changes to git
    versionNumber = get_version_number
    buildNumber = get_build_number
    tag = "#{versionNumber}.#{buildNumber}"

    # git_add
    git_add(path: ["./Podfile.lock", "./GShop.xcodeproj", "./GShopTests/Info.plist", "./GShop/Environments/Info.plist", "./GShopUITests/Info.plist"])
    git_commit(path: ["./Podfile.lock", "./GShop.xcodeproj", "./GShopTests/Info.plist", "./GShop/Environments/Info.plist", "./GShopUITests/Info.plist"], message: "verson up")
    add_git_tag(
      tag: tag
    )


  end
end
