//
//  ProductsInteractor.swift
//  GShop
//
//  Created by Matthew on 18.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsBusinessLogic {
    func doSomething(request: Products.Something.Request)
}

protocol ProductsDataStore {
    //var name: String { get set }
}

class ProductsInteractor: ProductsBusinessLogic, ProductsDataStore {
    var presenter: ProductsPresentationLogic?
    var worker: ProductsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Products.Something.Request) {
        worker = ProductsWorker()
        worker?.doSomeWork()
        
        let response = Products.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
