//
//  ProductsModels.swift
//  GShop
//
//  Created by Matthew on 18.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Products
{
    // MARK: Use cases
    
    enum Show {
        struct Request {
        }
        enum Response {
            case success([Product])
            case failure
        }
        struct ViewModel {
            var showModal: Bool = false
            var textMessage: String = ""
            let items: [Product]?
        }
    }
}
