//
//  ProductsRouter.swift
//  GShop
//
//  Created by Matthew on 18.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductsRoutingLogic {
    func routeToProduct(segue: UIStoryboardSegue?)
}

protocol ProductsDataPassing {
    var dataStore: ProductsDataStore? { get }
}

class ProductsRouter: NSObject, ProductsRoutingLogic, ProductsDataPassing {
    weak var viewController: ProductsViewController?
    var dataStore: ProductsDataStore?
    
    // MARK: Routing
    
    func routeToProduct(segue: UIStoryboardSegue?) {
        if let segue = segue {
            guard
                let destinationVC = segue.destination as? ProductViewController,
                let router = destinationVC.router,
                var destinationDS = router.dataStore
            else
                { return }
            passDataToProduct(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            guard
                let destinationVC =
                    storyboard.instantiateViewController(withIdentifier: "ProductViewController") as? ProductViewController
            else
                { return }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToProduct(source: dataStore!, destination: &destinationDS)
            navigateToProduct(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    func navigateToProduct(source: ProductsViewController, destination: ProductViewController) {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    func passDataToProduct(source: ProductsDataStore, destination: inout ProductDataStore) {
        destination.productId = source.selectedProductId
    }
}
