//
//  ProductsInteractor.swift
//  GShop
//
//  Created by Matthew on 18.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsBusinessLogic {
    func fetchProducts(request: Products.Show.Request)
    func addToCart(request: Products.AddToCart.Request)
}

protocol ProductsDataStore {
    var selectedProductId: Int? { get set }
}

class ProductsInteractor: ProductsBusinessLogic, ProductsDataStore {
    var selectedProductId: Int?
    var presenter: ProductsPresentationLogic?
    var fetchProductsWorker: CatalogDataRequestFactory?
    var addToCartWorker: CartItemsCreateRequestFactory?
    var analyticsWorker: AnalyticsService?
    
    // MARK: Do something
    func addToCart(request: Products.AddToCart.Request) {
        addToCartWorker?.create(
            productId: request.productId,
            quantity: 1,
            completionHandler: { resp in
                switch resp.result {
                case .success(let model):
                    self.analyticsWorker?.addItemToCart(request.productId)
                    self.presenter?.presentAddToCart(response: .success)
                case .failure:
                    self.presenter?.presentAddToCart(response: .failure)
                }
            }
        )
    }
    
    
    func fetchProducts(request: Products.Show.Request) {
        fetchProductsWorker?.catalogData(
            page: 1,
            perPage: 100,
            completionHandler: { resp in
                switch resp.result {
                case .success(let model):
                    self.analyticsWorker?.showItemsList()
                    self.presenter?.presentFetchProducts(response: .success(model.items))
                case .failure:
                    self.presenter?.presentFetchProducts(response: .failure)
                }
            }
        )
    }
    
    
}
