//
//  ProductsPresenter.swift
//  GShop
//
//  Created by Matthew on 18.03.2021.
//  Copyright (c) 2021 Ostagram Inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductsPresentationLogic
{
  func presentSomething(response: Products.Something.Response)
}

class ProductsPresenter: ProductsPresentationLogic
{
  weak var viewController: ProductsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Products.Something.Response)
  {
    let viewModel = Products.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
